project:
  type: website
  output-dir: docs

website:
  title: "Christianna L. Lindsay"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Resume.qmd


format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

